backend:
  name: git-gateway
  branch: master # Branch to update (optional, defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "global-settings"
    label: "Global Settings"
    folder: "_data"
    file: "global-settings.yml"
    create: false
    delete: false
    fields:
      - {label: "Site Name", name: "siteName", widget: "string"}
      - {label: "Contact Phone", name: "contactPhone", widget: "string"}
      - {label: "Contact Email", name: "contactEmail", widget: "string"}
      - {label: "Contact Whatsapp", name: "contactWhatsapp", widget: "string"}
      - {label: "Site Logo", name: "logo", widget: "image", required: false}

  - name: "hero-slides"
    label: "Hero Slides"
    folder: "_data/hero-slides"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Background Image", name: "backgroundImage", widget: "image"}
      - {label: "Button Text", name: "buttonText", widget: "string", required: false}
      - {label: "Button Link", name: "buttonLink", widget: "string", required: false}
      - {label: "Order", name: "order", widget: "number", value_type: "int", min: 0, step: 1}
      - {label: "Active", name: "active", widget: "boolean", default: true}

  - name: "properties"
    label: "Properties"
    folder: "_data/properties"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", hint: "Unique identifier for the property URL (e.g., luxury-apartment-london)"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Category", name: "category", widget: "string", required: false}
      - {label: "Price From", name: "priceFrom", widget: "string", required: false}
      - {label: "Yield", name: "yield", widget: "string", required: false}
      - {label: "Deposit", name: "deposit", widget: "string", required: false}
      - {label: "Completion Date", name: "completionDate", widget: "string", required: false}
      - {label: "Tenure", name: "tenure", widget: "string", required: false}
      - {label: "Total Units", name: "totalUnits", widget: "string", required: false}
      - {label: "Featured Property", name: "featured", widget: "boolean", default: false, hint: "Check to display on homepage"}
      - {label: "Main Image", name: "mainImage", widget: "image"}
      - {label: "Gallery", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"}, required: false}
      - {label: "Map Location (Embed Code)", name: "mapLocation", widget: "text", required: false, hint: "Embed code for Google Maps or similar"}

  - name: "pages"
    label: "Pages"
    folder: "_data/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", hint: "Unique identifier for the page URL (e.g., about-us, contact)"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Hero Image", name: "heroImage", widget: "image", required: false}
      - {label: "Map Location (Embed Code)", name: "mapLocation", widget: "text", required: false, hint: "Embed code for Google Maps or similar"}
      - {label: "Image Slides", name: "imageSlides", widget: "list", field: {label: "Image", name: "image", widget: "image"}, required: false}


collections:
  - name: "hero-slides"
    label: "Hero Slides"
    folder: "content/hero-slides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Button Text", name: "buttonText", widget: "string", required: false }
      - { label: "Button Link", name: "buttonLink", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number" }
      - { label: "Active", name: "active", widget: "boolean" }
